name: Compile hugo project
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        git submodule update --init --recursive
    - uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify --buildDrafts
    - name: Commit compiled project to release
      run: |
        git diff
        git config --global user.name 'Automaton'
        git config --global user.email 'asenj.mihaylov@gmail.com'
        git add .
        git commit -m "Automated report"
        git push
