name: Compile hugo project
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify --buildDrafts
    - name: Commit compiled project to release
      run: |
        git config --global user.name 'Automaton'
        git config --global user.email 'asenj.mihaylov@gmail.com'
        git commit -am "Automated report"
        git push
